### PR TITLE
VRF support

### PR DESCRIPTION
**Pull request by robschn**
Awesome script! My environment uses VRFs, so added support for that. An option to use the script without VRFs would need to be added.

### CODE REVIEW

**Comment by routetehpacketz** [comment]
hey Robert, thank you for the contribution! 

it appears the script does not function if no VRF is entered. I keep getting "No MAC for x.x.x.x" if I do not enter a VRF

I believe we will need to alter the script to first prompt if a VRF is needed and then alter the ping command to include the vrf option if necessary. 

what are your thoughts on this?

**Comment by robschn** [comment]
I added an if statement for the VRF prompt and made vrf into a variable. If the user hits enter, it'll make vrf == "" and current_vrf == "", if not it'll make vrf == "vrf" and use the input from current_vrf. 

Seems to work for me, how about you?

**Comment by routetehpacketz** [comment]
I believe the ARP table lookup is failing when no VRF is provided since the command has been changed to `show ip arp vrf`

are you saying the script runs for you successfully if you do not provide a VRF?

**Comment by robschn** [comment]
My latest commit will remove the vrf part from `show ip arp` if not vrf is selected. The user just pressed 'Enter' when prompted.

**Pull request merged**
