### PR TITLE
CSV and CLI option Fork

### PR DESCRIPTION
**Pull request by jeanders**
Hello,

First of all, thanks for doing this script. I found it very helpful. I forked your script for my needs and wanted to give you the option to accept any changes if you find them useful.

- Added ability to run script via options instead of number based menus
- Added CSV output
- Refactored to more reusable functions

### CODE REVIEW

**Comment by routetehpacketz** [comment]
wow this is a great contribution! I had learned about `argparse` somewhat recently and knew it would benefit this script. 

I have two suggestions, though: 

1) I would like the output to csv to be optional. I often run this for single IP addresses, so having a csv file in these scenarios is really not needed.

2) If possible, I'd like the prompts to remain if the script is run without any parameters. 

Let me know what you think. I am going to take your version of the script and attempt these enhancements myself, but if you do as well I'd like to compare what we both come up with.

**Comment by jeanders** [comment]
@routetehpacketz Thanks! These both sound like good ideas to me. Let me know if you have issues making the modifications or need help. I'll see about attempting them as well.

**Comment by routetehpacketz** [comment]
so I think I have a working solution for both of the items I mentioned above. should I just push them to your master branch or do you want to create a "testing" branch before we finalize the changes?

I want to eventually merge your master branch in with mine.

**Comment by jeanders** [comment]
I created a testing branch to push to.

Thanks!

**Comment by routetehpacketz** [comment]
thanks! do you need to grant me access to it? I am getting a "permission denied" when trying to push to the testing branch. I'm pretty much a noob when it comes to using git appropriately so I could be doing something wrong.

**Comment by jeanders** [comment]
On further inspection it looks like you should actually have permissions on the branch I sent the pull request from, so if you want to give a go on master, go for it. I think I would otherwise have to restart the pull request from testing.

**Comment by routetehpacketz** [comment]
okay I think I just did it correctly. I haven't updated the README yet though. mostly all I did was put some if/else statements in to see if parameters were passed to the script and to use the `options` variables if so. otherwise is uses my original variable names from the interactive prompts.

let me know what you think.

**Comment by jeanders** [comment]
Looks good to me, and it is showing up in the pull so I think we're good process wise.

**Comment by routetehpacketz** [comment]
I just realized the alerting that the target IP provided is a CDP neighbor was omitted in your version of the script. I would like to add this back in as well. before I make any other changes, can you clarify what your intention was for this?

`cdp_air_check=re.search(air_regex,show_cdp_nei)
	if cdp_air_check:
		return False`

does this just end the trace on the current port if a Cisco AP is detected?

**Comment by jeanders** [comment]
Correct, I was having issues with the script trying to SSH into APs and failing. So, if the client is wireless it tracks it to the switch port connected to the AP.

**Pull request merged**
