### PR TITLE
Handling for enable passwords/secrets

### PR DESCRIPTION
**Pull request by routetehpacketz**
Related to issue #13, the script was never written to accommodate the need for an enable password.

### CODE REVIEW

**Comment by net9000** [comment]
Does this mean it the script supports an enable pw now?  Does it have a logic to know whether it needs to use one or not?

**Comment by routetehpacketz** [comment]
hey @net9000,

It's good to see you are still subscribed to this repo :+1: 

Yes, this pull request is to add the ability to supply an enable password/secret. I am still confirming, but I believe the logic of determining whether or not one is needed is inherit to the Cisco CLI. If you are already in enable mode, the issuance of an enable password does nothing.

In preparing for this, it seems the `netmiko` Python module will re-use the supplied _user_ password as the enable password if no specific enable password is supplied. I am going to update the README to reflect both of these pieces of information.

If you want to conduct some testing with me, the latest version of the script from this pull request is [here](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/d9b9e91db33521b5d5aa221bf251058ecad180d1/cisco_ip_trace.py).

**Comment by net9000** [comment]
@routetehpacketz I will test it and let yo know.

**Comment by routetehpacketz** [comment]
hey, @net9000. I just wanted to follow up to see if you have been able to test this.

**Comment by net9000** [comment]
@routetehpacketz will today, where is the updated script?

**Comment by routetehpacketz** [comment]
The changes have been merged!

**Pull request merged**
